'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
require('../scripts/build.cjs');
let count=0;
function check(name,fn){fn();count++;console.log('PASS '+name)}
function render(handler,url='/',query={}){const response={headers:{},statusCode:200,setHeader(k,v){this.headers[k.toLowerCase()]=v},status(c){this.statusCode=c;return this},send(s){this.body=s}};require('../api/'+handler)({url,query,headers:{}},response);return response}
check('JavaScript sources parse',()=>{for(const folder of ['api','lib','assets','scripts'])for(const f of fs.readdirSync(path.join(root,folder))){if(/\.(js|cjs)$/.test(f))new vm.Script(fs.readFileSync(path.join(root,folder,f),'utf8'),{filename:folder+'/'+f})}new vm.Script(fs.readFileSync(path.join(root,'portal-enhanced.js'),'utf8'))});
const home=render('index');
check('Home is server-rendered with one H1 and meaningful title',()=>{assert.equal(home.statusCode,200);assert.equal((home.body.match(/<h1[ >]/g)||[]).length,1);assert.match(home.body,/<title>Chevening Application Preparation/);assert.match(home.body,/Make it visible/)});
check('All home fragment targets exist',()=>{const hrefs=[...home.body.matchAll(/href="#([^"]+)"/g)].map(x=>x[1]);for(const id of hrefs)assert(home.body.includes('id="'+id+'"'),id)});
check('Public source asset references exist',()=>{for(const r of [...home.body.matchAll(/(?:src|href)="(\/(?:assets\/)[^"?]+)(?:\?[^\"]*)?"/g)])assert(fs.existsSync(path.join(root,r[1])),r[1])});
check('Structured data is parseable and allowed by a matching CSP hash',()=>{const json=home.body.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1];const graph=JSON.parse(json);assert(graph['@graph'].some(x=>x['@type']==='Organization'));const hash=crypto.createHash('sha256').update(json).digest('base64');assert(home.headers['content-security-policy'].includes("'sha256-"+hash+"'"));assert(!json.includes('aggregateRating'))});
check('Live purchase and AI status are not invented',()=>{assert.match(home.body,/purchases not yet open/);assert.match(home.body,/fictional/i);const method=render('resources','/methodology',{page:'methodology'});assert.match(method.body,/planned but disabled/);assert.match(method.body,/not a semantic AI assessment|not an AI model|not currently connected/)});
check('Six useful guide pages render and cite official guidance',()=>{const guides=require('../lib/guides');assert.equal(Object.keys(guides).length,6);for(const slug of Object.keys(guides)){const r=render('resources','/guides/'+slug,{page:'guides',slug});assert.equal(r.statusCode,200);assert.match(r.body,/chevening\.org/);assert.match(r.body,/"@type":"Article"/);assert.equal((r.body.match(/<h1[ >]/g)||[]).length,1)}});
check('Unknown and prototype-key guides return 404',()=>{for(const slug of ['missing','__proto__','constructor'])assert.equal(render('resources','/guides/'+slug,{page:'guides',slug}).statusCode,404)});
check('Help and legal pages render with CSP',()=>{for(const h of ['privacy','terms']){const r=render(h,'/'+h);assert.equal(r.statusCode,200);assert(r.headers['content-security-policy']);assert.match(r.body,/\/help/)}const r=render('resources','/help',{page:'help'});assert.match(r.body,/id="support-form"/);assert.match(r.body,/minlength="10"/)});
check('Private workspace cannot be indexed and is not cached publicly',()=>{const r=render('portal','/app');assert.match(r.headers['x-robots-tag'],/noindex/);assert.match(r.headers['cache-control'],/no-store/);assert.match(r.body,/portal-enhanced\.js/);assert(r.headers['content-security-policy'])});
check('Sitemap excludes authentication and private workspace',()=>{const r=render('sitemap');assert(!r.body.includes('/app<'));assert(!r.body.includes('/login'));assert.equal((r.body.match(/<url>/g)||[]).length,13)});
check('Preview deployments discourage indexing',()=>{const old=process.env.VERCEL_ENV;process.env.VERCEL_ENV='preview';assert.match(render('robots').body,/Disallow: \/\n/);assert.match(render('index').body,/content="noindex,follow"/);if(old===undefined)delete process.env.VERCEL_ENV;else process.env.VERCEL_ENV=old});
check('Portal fixes are in generated runtime',()=>{const s=fs.readFileSync(path.join(root,'portal-enhanced.js'),'utf8');assert(!s.includes('"${c.answered}/4 core answers added"'));assert(!s.includes('Math.max(0,stories-1)'));assert(s.includes('scholar_methodology:false'));assert(s.includes('demoURL("/app/application?criterion="'));assert(s.includes('resendConfirmation'));assert(s.endsWith('init();\n'))});
console.log(`${count} release checks passed.`);
