'use strict';
const crypto = require('node:crypto');
const ORIGIN = 'https://axalidavaleba4.vercel.app';
const VERSION = '20260929-workflows';
const official = {
 criteria: 'https://www.chevening.org/resource-hub/guidance/application-criteria/',
 ai: 'https://www.chevening.org/faqs/can-i-use-ai-to-help-me-write-my-application/',
 prepare: 'https://www.chevening.org/resource-hub/guidance/prepare-your-application/',
 timeline: 'https://www.chevening.org/scholarships/application-timeline/',
 eligibility: 'https://www.chevening.org/resource-hub/guidance/eligibility/'
};
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>';
const check = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>';
const mark = '<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M7 6h13l5 5v15H7z"/><path d="M19 6v7h6M11 19l3 3 7-7"/></svg>';
const brand = () => `<a class="brand" href="/" aria-label="ShortlistProof home"><span class="brand-mark">${mark}</span>Shortlist<span>Proof</span></a>`;
function header(){return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container nav-shell">${brand()}<button class="menu-toggle" id="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav"><span>Menu</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><nav id="site-nav" aria-label="Main navigation"><a href="/#how-it-works">How it works</a><a href="/guides">Guides</a><a href="/stories">Alumni stories</a><a href="/#pricing">Pricing</a><a href="/login" class="nav-signin">Sign in</a><a href="/#free-check" class="button button-small">Start free ${arrow}</a></nav></div></header>`;}
function footer(){return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div>${brand()}<p>Make the experience you already have<br>easier for a reader to understand.</p><span class="footer-note">Your story. Your words. Better questions.</span></div><div><h2>Explore</h2><a href="/#free-check">Free application check</a><a href="/app?demo=1">Explore the workspace</a><a href="/#pricing">Plans &amp; availability</a></div><div><h2>Learn</h2><a href="/guides">Chevening preparation guides</a><a href="/stories">Public alumni stories</a><a href="/methodology">How our checks work</a><a href="/help">Help &amp; account access</a></div><div><h2>The essentials</h2><a href="${official.criteria}" target="_blank" rel="noopener noreferrer">Official Chevening criteria ${arrow}</a><a href="${official.ai}" target="_blank" rel="noopener noreferrer">Official AI-use policy ${arrow}</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></div><div class="footer-bottom"><span>&copy; ${new Date().getUTCFullYear()} ShortlistProof</span><p>Independent preparation support. Not affiliated with or endorsed by Chevening, FCDO, the UK Government or any university. Applying to Chevening is free. Our optional tools do not submit an application or guarantee an award.</p></div></div></footer>`;}
const faqs = [
 ['Is ShortlistProof an official Chevening service?', 'No. ShortlistProof is an independent preparation tool. Chevening does not endorse or work with third parties who charge for application support. You can apply for free using its official website.'],
 ['Will it write or rewrite my essays?', 'No. Your application must be your own original work. Our checks identify possible evidence gaps and ask reflection questions; they do not generate, rewrite or paraphrase submission answers. Chevening prohibits AI-generated application answers.'],
 ['What does the free check actually do?', 'It looks for a small set of wording cues in one self-written answer. It then suggests what to review. This is a transparent, rule-based reflection aid, not an AI assessment, a verified quality score or a prediction of selection.'],
 ['Is the text I paste into the free check saved?', 'The public free check processes your text in your browser. It does not upload the answer or save it to an account. When you deliberately save work inside a signed-in workspace, that work is stored in your account.'],
 ['Can I try the workspace before creating an account?', 'Yes. The interactive demo uses clearly labelled fictional sample data. You can explore the workflow without signing in. Demo changes are not saved to a real account.'],
 ['Can I buy Full access now?', 'Not yet. The planned price is GBP 39 once for one application cycle, but live purchases are not open. Start with the free check or explore the Full demo. No payment is needed to try either.']
];
function faqHTML(){return `<section class="section" id="faq"><div class="container faq-layout"><div><span class="eyebrow">Clarity before commitment</span><h2>A few things<br>worth knowing.</h2><p>Know exactly what you are using<br>and what you are not.</p></div><div class="faq-list">${faqs.map(([q,a])=>`<details><summary>${esc(q)}<span aria-hidden="true">+</span></summary><div><p ${q==='Can I buy Full access now?'?'data-full-faq':''}>${esc(a)}</p></div></details>`).join('')}</div></div></section>`;}
function sendPage(req,res,options,content,status=200){
 const {title,description,path='/',schema=null}=options;
 if(path==='/')content=require('./stories').enhanceHome(content);
 const noindex=options.noindex || process.env.VERCEL_ENV==='preview';
 const graph=[{'@type':'Organization','@id':ORIGIN+'/#organization',name:'ShortlistProof',url:ORIGIN,logo:ORIGIN+'/assets/mark.svg'},{'@type':'WebSite','@id':ORIGIN+'/#website',name:'ShortlistProof',url:ORIGIN,publisher:{'@id':ORIGIN+'/#organization'}},{'@type':'WebPage','@id':ORIGIN+path,name:title,url:ORIGIN+path,description,isPartOf:{'@id':ORIGIN+'/#website'}},...(schema?[schema]:[])];
 const json=JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c');
 const hash=crypto.createHash('sha256').update(json).digest('base64');
 res.setHeader('Content-Type','text/html; charset=utf-8');
 res.setHeader('Cache-Control','public, max-age=0, must-revalidate');
 res.setHeader('Content-Security-Policy',`default-src 'self'; script-src 'self' 'sha256-${hash}'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://gqbzaiqppyxweuxpbowl.supabase.co; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests`);
 res.status(status).send(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow,max-image-preview:large'}"><meta name="theme-color" content="#142b42"><link rel="canonical" href="${ORIGIN+path}"><link rel="icon" href="/assets/mark.svg" type="image/svg+xml"><meta property="og:type" content="website"><meta property="og:site_name" content="ShortlistProof"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${ORIGIN+path}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Source+Serif+4:opsz,wght@8..60,500;8..60,600&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/site.css?v=${VERSION}"><link rel="stylesheet" href="/assets/conversion.css?v=${VERSION}"><script type="application/ld+json">${json}</script><script src="/assets/auth-handoff.js"></script><script src="/assets/site.js?v=${VERSION}" defer></script><script src="/assets/billing-availability.js?v=${VERSION}" defer></script></head><body>${header()}${content}${footer()}</body></html>`);
}
module.exports={ORIGIN,VERSION,official,esc,arrow,check,brand,header,footer,faqs,faqHTML,sendPage};
