"use strict";
const {esc,arrow}=require('./site');
const stories=[
 {name:'Raju Kendre',place:'India',theme:'Widening access to education',date:'12 November 2024',source:'https://www.chevening.org/news/breaking-down-barriers-how-raju-kendre-is-redefining-opportunities-for-indias-marginalised-communities/',summary:'Raju founded Eklavya India Foundation to support first-generation university students from marginalised communities. Chevening’s profile records his 2021 scholarship and Development Studies master’s at SOAS.',question:'What problem do you understand through your own experience, and what have you already done about it?'},
 {name:'Eunice Ntobedzi Hanna',place:'Botswana',theme:'Building a clean-energy business',date:'18 June 2024',source:'https://www.chevening.org/news/celebrating-our-chevening-alumni/',summary:'Chevening’s 2024 alumni feature describes how Eunice co-founded African Sun Energy and expanded its clean-energy work across Botswana, Malawi and Zambia.',question:'Which specific decisions show how you turned an ambition into practical work?'},
 {name:'Maya Terro',place:'Lebanon',theme:'Connecting food rescue with hunger relief',date:'18 June 2024',source:'https://www.chevening.org/news/celebrating-our-chevening-alumni/',summary:'The same alumni feature highlights Maya’s work co-founding FoodBlessed, an organisation that combines hunger relief with food rescue through meals and food parcels.',question:'Who benefits from your work, and what evidence makes that contribution visible?'}
];
function cards(reflection=false){return stories.map((s,i)=>`<article class="alumni-card"><div class="alumni-card-top"><span class="alumni-number" aria-hidden="true">0${i+1}</span><span class="eyebrow">${esc(s.place)}</span></div><h3>${esc(s.theme)}</h3><p class="alumni-name">${esc(s.name)}</p><p>${esc(s.summary)}</p>${reflection?`<div class="alumni-reflection"><b>A question for your own preparation</b><p>${esc(s.question)}</p><small>ShortlistProof reflection prompt, not advice from the person profiled.</small></div>`:''}<a class="text-link" href="${s.source}" target="_blank" rel="noopener noreferrer">Read the official profile ${arrow}</a><p class="alumni-source">Chevening publication: ${esc(s.date)}<br>Public alumni story. Not a ShortlistProof testimonial.</p></article>`).join('')}
function homeSection(){return `<section class="section alumni-section" id="alumni-stories"><div class="container"><div class="split-head"><div><span class="eyebrow">Real people. Different kinds of contribution.</span><h2>There is no single shape<br>to <em>a meaningful story.</em></h2></div><p>Explore public Chevening alumni profiles, then return to the experience only you can describe.</p></div><div class="source-note"><p>These independent summaries are drawn from Chevening’s published profiles. The people featured are not presented as our customers or endorsers. Their achievements are not outcomes of using ShortlistProof.</p></div><div class="alumni-grid">${cards()}</div><a class="text-link alumni-all" href="/stories">Explore the stories and reflection questions ${arrow}</a></div></section>`}
function enhanceHome(content){
 const fit=`<section class="section fit-section"><div class="container fit-grid"><div><span class="eyebrow">Choose the support you actually need</span><h2>More structure.<br><em>Still entirely your work.</em></h2><p>You are not paying for somebody else’s words. Full access brings your evidence, comparisons and final review into the same workspace.</p></div><div class="fit-card"><h3>A good fit when you want to...</h3><p>Choose between your own examples, keep four drafts connected, and return to a clear next step instead of another blank page.</p><h3>Not a fit when you want...</h3><p>Written answers, official approval or a promise of a scholarship. We do not offer any of those.</p><a class="text-link" href="/app?demo=1">Try the workflow before deciding ${arrow}</a></div></div></section>`;
 const anchor='<section class="section" id="faq">';
 return content.replace(anchor,fit+homeSection()+anchor)
 .replace('<span class="plan-state">Full preview','<span class="plan-state" data-full-state>Full preview')
 .replace('Planned price &middot; once per application cycle.','<span data-full-price-note>Planned price &middot; once per application cycle.</span>')
 .replace('<a class="button button-gold" href="/app?demo=1">','<a class="button button-gold" data-full-cta href="/app?demo=1">')
 .replace('<p class="plan-note">No charge. No subscription. Live checkout is not open.</p>','<p class="plan-note" data-full-note>No charge. No subscription. Live checkout is not open.</p>')
 .replace('Story Bank, Whole Case and Final Proof are available to explore in the Full demo. Live Full purchases are not open yet.','<span data-full-feature-note>Story Bank, Whole Case and Final Proof are available to explore in the Full demo. Live Full purchases are not open yet.</span>');
}
module.exports={stories,cards,homeSection,enhanceHome};
